Common API C Tools
==================

Purpose and Features
--------------------
Common API C tools include code generators that take Franca IDL files as input and produce C code that is compatible with the run-time support library.  This functionality is available as either standalone binaries (for Linux and Windows platforms) or Eclipse plug-ins.  The former can be used as a part of the build tool chain and requires only Java Runtime to be installed.  The latter extends Eclipse UI with commands to generate Common API C from Franca IDL (`.fidl`) files.


Dependencies and Installation
-----------------------------
Java 1.7 and Maven 3.3+ must be installed in order to build the Eclipse plug-ins and standalone code generators for Common API C.  All other dependencies will be downloaded during the build automatically.  From the project root directory, a complete clean build can be performed as follows:

----
$ cd tools/org.genivi.capic.core.parent ; mvn clean verify
----

After a successful build, the standalone generators for various platforms can be found under `tools/org.genivi.capic.core.product/target/products/org.genivi.capic.core.product/` and the update site for Eclipse plug-ins can be found under `tools/org.genivi.capic.core.updatesite/target/repository/`.


Coding Style
------------
All Java code uses the Eclipse formatting profile '`Eclipse Spaces Only`'.

All Xtend code use the default Xtend formatting profile.  (Although the latter uses tabs for indentation there seems to be no way to change this in Eclipse configuration.)


Development with Eclipse IDE
----------------------------
Use _Eclipse IDE for Java and DSL Developers_ release _Mars_ or later available from the http://www.eclipse.org[Eclipse Project] or equivalent.  Additionally to this:

* Install _Tycho Configurator_ to support RCP and Eclipse plugin development.  Go to `Window > Preferences`, select `Maven > Discovery` and click on `Open Catalog`.  Find and select the `Tycho Configurator`.

* Install _Eclipse e4 Tools Developer Resources_ to support e4 application development (such as `rcp` file generation).  Install via `Help > Install New Software...` directly from the preconfigured Mars update site.  (For Eclipse releases prior to Mars use http://download.eclipse.org/e4/updates/[].)

* Install _Franca Runtime_ and _Franca UI_ to use Franca support libraries.  Go to `Help > Install New Software...`, click on `Add...`, add http://franca.github.io/franca/update_site/releases/[Franca update site] and install the plugins.

After completing these steps, it should be possible to import all tooling sub-projects, run the unit tests in `org.genivi.capic.core.test` and build and run the UI plugin in `org.genivi.capic.core.ui`.

Since Maven is considered the primary tool for building Common API C Tools, the content of `.settings/` directories is generally not tracked under version control.  Some subprojects make exception to this rule for certain types of settings.
